services:

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    env_file: .env
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - server
